# Dependencies
markdown:         kramdown

# Setup
title:            Grab The Blaster
description:      Un blog nerd il giusto di Alessio Biancalana
tagline:          di Alessio Biancalana
paginate:         5
paginate_path:    '/page/:num'
baseurl:          ''
url:              'http://dottorblaster.it'
permalink:        '/:year/:month/:title/'
excerpt_separator: ""
license:
  link:           'https://creativecommons.org/licenses/by-nc/3.0/'
  label:          'CC BY-NC'
author:
  name:           Alessio Biancalana
  url:            http://dottorblaster.it
  email:          dottorblaster@gmail.com

# Custom vars
version:          0.3.0
github:
  repo:           https://github.com/dottorblaster/dottorblaster.github.io

# Custom configs
plugins: [jekyll-paginate]

exclude:
  - Gemfile
  - Gemfile.lock
  - Thorfile
  - vim_provision.sh
  - vimrc.vim
  - README.md
  - LICENSE.md
  - CNAME
  - .gitignore
  - vendor
