# Dependencies
markdown:         redcarpet

# Setup
title:            Grab The Blaster
tagline:          di Alessio Biancalana
paginate:         5
baseurl:          '/'
url:              'http://dottorblaster.it'
permalink:        '/:year/:month/:title'
author:
  name:           Alessio Biancalana
  url:            http://dottorblaster.it
  email:          dottorblaster@gmail.com

# Custom vars
version:          0.0.7
github:
  repo:           https://github.com/poole/poole
